#include "character.hpp"
#include "healer.hpp"
#include "Item.hpp"
#include "mage.hpp"
#include "warrior.hpp"

int main() {
    std::cout << "========== MAGE OBJECT TEST ==========" << std::endl << std::endl;

    // Create a Mage object
    Mage mage("Gandalf", 5, 100, false);

    std::cout << "--- Basic Information ---" << std::endl;
    std::cout << "Name: " << mage.getName() << std::endl;
    std::cout << "Level: " << mage.getLevel() << std::endl;
    std::cout << std::endl;

    // Test levelUp
    std::cout << "--- Testing levelUp ---" << std::endl;
    std::cout << "Current Level: " << mage.getLevel() << std::endl;
    mage.levelUp(3);
    std::cout << "After levelUp(3): " << mage.getLevel() << std::endl;
    std::cout << std::endl;

    // Test levelDown
    std::cout << "--- Testing levelDown ---" << std::endl;
    mage.levelDown(1);
    std::cout << "After levelDown(1): " << mage.getLevel() << std::endl;
    std::cout << std::endl;

    // Test healthUp
    std::cout << "--- Testing healthUp ---" << std::endl;
    mage.healthUp(50);
    std::cout << "Health increased by 50" << std::endl;
    std::cout << std::endl;

    // Test healthDown
    std::cout << "--- Testing healthDown ---" << std::endl;
    mage.healthDown(20);
    std::cout << "Health decreased by 20" << std::endl;
    std::cout << std::endl;

    // Test regenManaPoints (Mage specific)
    std::cout << "--- Testing regenManaPoints (Mage specific) ---" << std::endl;
    mage.regenManaPoints(100);
    std::cout << "Mana regenerated by 100 points" << std::endl;
    std::cout << std::endl;

    // Test isInventoryFull
    std::cout << "--- Testing isInventoryFull ---" << std::endl;
    if (mage.isInventoryFull()) {
        std::cout << "Inventory is full" << std::endl;
    } else {
        std::cout << "Inventory has space" << std::endl;
    }
    std::cout << std::endl;

    Item ball("Ball");
    mage.addItemToInventory(ball);
    std::cout << "Item at Index 0: " << mage.getItemfromInventory(0).getNameString() << std::endl;    

    std::cout << "========== END OF TESTS ==========" << std::endl;

    return 0;
}
